[tool.poetry]
name = "pythonpwgenerator"
version = "0.1.0"
description = ""
authors = ["mottonen12n <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pylint = "^2.12.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
